---
- name: Ubuntu specific sanity
  block:
  - name: Verify ufw is running
    service: 
      name: ufw
      state: started

- name: Verify ntp is running
  service:
    name: ntp
    state: started

- name: Verify apparmor is running
  service:
    name: apparmor
    state: started

